# Unix or TCP socket to listen for web requests
listen: 8080

# Group of the Unix socket
group: www-data

# Root of the publicly facing web server to prepend links
base: /

# A secret used to sign authorization tokens
authsecret: "ggVUtPQdIL3kuMSeHQgn7PW9nv3XuJBp"

# The SHA-256 hash of the password to gain admin access
authdigest: 11a55ac5de2beb9146e01386dd978a13bb9b99388f5eb52e37f69a32e3d5f11e

# The MaxMind GeoDB used for geofencing
geodb: GeoLite2-City.mmdb

# The databases to include for categorical blacklisting
databases:
    datacenters: ../ipcat/datacenters.csv
    tor: ../ipcat/tor.csv

# The directory to upload files to
uploaddirectory: ./uploads/

# The permissions to set for file uploads
uploadpermissions: 0600

# The maximum form and file upload size in bytes
uploadmaxsize: 1000000
